name: game_price_checker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.3.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.0.0
  cheapshark_games_api:
    path: packages/cheapshark_games_api
  equatable: ^2.0.5
  firebase_core: ^2.32.0
  firestore_favorites_api:
    path: packages/firestore_favorites_api
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.7.0
  games_api:
    path: packages/games_api
  games_repository:
    path: packages/games_repository
  http: ^1.3.0
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
