name: authentication_repository
description: Dart package taht handles the authentication
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  meta: ^1.12.0
  shared_preferences: ^2.2.3

dev_dependencies:
  firebase_auth_platform_interface: ^7.2.7
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
