name: form_inputs
description: Helper package for handling form inputs
version: 0.1.0+1
publish_to: none

environment:
  sdk: '^3.3.0'
  flutter: '^3.19.0'

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.7.0

dev_dependencies:
  very_good_analysis: ^5.1.0
